spring:
  application:
    name: gateway-server
zuul:
  routes:
    users:
      path: /users/**
      service-id: user-service
      strip-prefix: false
      

eureaka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    eureka-server-read-timeout-seconds: 100
    
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 100000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timoutInMilliseconds: 900000
            
            
server:
  port: 8765